apiVersion: 1

datasources:
  - name: Ventures Postgres
    type: postgres
    uid: postgres_ventures
    access: proxy
    url: relational_db:5432
    database: ventures_db
    user: postgres
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres
